			Wind Shear Gust System

	Description : Powerful, unpredictable wind currents sweep across the cliff faces, generated by pressure differentials between the uplands and the sea below. 
These gusts move in irregular pulses rather than constant streams.

	Mechanics : 
* Wind gusts trigger at intervals, not constantly
* Gust direction varies based on cliff curvature
* Strong gusts can:
  * Push players sideways
  * Interrupt casting
  * Reduce movement control near edges

	Player Interaction : 

* Players must:
	* Time movement between gusts
	* Use terrain (rocks, overhangs) as wind breaks
* Heavier armor reduces displacement but increases stamina drain

	Feedback : 
* Audio: rising wind howl before activation
* Visual: dust, loose pebbles, grass bending sharply

---
