			Companion Mechanics 
			
	Companions can be direct controled by pressing down "Left ALT" where switch to direct control of them. In this stance the "Action Bar" switch to pet control 
action that is same as controling a normal "PET".
	To switch between companion and pet, as between both pets when are called by other races, must click the pet target first and then press down "Left ALT". To 
reset just simple click on your character.
	Companions are used only in PvM stance and are not involved in any PvP stance.
	
		About them : 
	Those are joyfull animals once they are tamed and change their traits once are summoned for the first time.
	Once they die, a cooldown of 5 minutes is applied globaly.
	Once they are tamed, they start with level 1 as every pet. Their level cap is 90, same as every pet. They grow in size same as every other pet.
	Companions follow their master always when they are summoned.
	Companions dont starve but they eat parts of "Blood Orbs" that the "Vampires" absorb from their targets, used to maintain their strainght.
	Companions have unique emotes and actions that can be accessed from "Page 3" by their masters. They have a pack of emotions that sometimes they do it by 
themself and use sounds. end 

		Companions Type : 
	They have a huge pool of HP but this also depends what kind of pet they are : 
*Tanker class have the biggest HP poll bar but also the highest ACC. Their aggro mechanics is better than others and immune to most of CCs, except Stuns. Their 
attacks are not high but resist perfect even in a battle with 10+ monsters with +3 levels higher.
*Striker class is the second as HP poll bar with a lower ACC but they have the highest attack damage. They are immune to "Slow CCs" only. They are more agile than 
others and the higher level have, the higher penetration damage deal. 
*Healer class is very low in HP poll bar and their attack is the weakest. They have the highest mobility. Their only ability apart from tanking and holding back the
targets, they heal 1% the master every 3 seconds. Improved, they can heal the master more % according with the damage that the master receive.
*Ranger class is a very versatile class, they are the rarest. They are range attackers and can Aggro the most targets among the others. They have medium HP poll bar
and their mechanics are to lure the targets in cercles and send strikes as range damage. Also they have a good mobility.

		Power and Abilities : 
	This companions ignore any ACC that the monsters have it.
	Companions have already +10% Resistance to all Elements.
	Companions have already +10% Magic Resistance.
	Companions can be harm by "DoTs" and eventually can die.
	Companions have skills,which are unique to their type and also they can learn some extra when they level up.
	Companions have talents that come with but can be improved when they level up. Also this can be reset and use the points back to chose new ones.
	Companions cannot be heal by external sources.
	Companions cannot be targetedby others except their own masters.
	Some companions impact the game in some way. In particular, companions do not stealth. If your character uses stealth, your companion will reveal your presence.
Mobs do not notice companions, so having one can be useful to indicate your location to party members.  end end end 

	Companions use active skills that deal only physical damage. Each companion come with 3 attacks as : 
*Once AoE skill that is main with a long cooldown. This skill use its own "Rage".
*Push skill that have a shorter cooldown.
*Dash or explosive skill that is used only when really necessary. 

	Rage is generated by receiving damage from monsters. The more targets attack him, the faster the "Rage" charge. Is not charging from "Special monsters", 
"Bosses" , "Special Bosses" , "Rare monsters" , "WB" or other high ranked monsters.
	Health is recharge nack when is out of combat.
	Mana is used by other 2 skills and is recharging slowly even during in combat.
	
	Companions can jump and swim but cannot dive deep otherwise they are send back automatically. Also they receive massive damage when they fall from high 
locations and most of the time, they die instant.
	When their heal is under 20% they stop being Aggro to many targets and all others are going to attack their master.
	Their HP bar like other kind of pets is green, but become orange when goes under 75% until 20% when turns red. When is red, most of the attributes are reduced.