			Ironhoof the Ravager

**Element:** Wind / Earth
**Combat Role:** Area Disruptor & Siege Breaker
**Arena:** Banham Highlands 
**Resource Type:** Rage (generated by receiving damage or being surrounded by multiple opponents)

---

### 🪓 **Lore & Appearance**

Legends say **Ironhoof** was once the sacred guardian of Banham’s mountain forges — a minotaur chieftain who swore an oath to protect the ancient furnaces of the dwarves.
When the forges fell silent, he fused his body with molten iron to preserve his strength for eternity. Now, his veins run with magma, his eyes burn like embers, and each stomp of his hooves cracks the ground beneath him.

---

### ⚔️ **Combat Overview**

Ironhoof is a **frontline juggernaut** built to devastate clustered groups and defensive formations.
He gains **Rage** from sustained damage and uses it to unleash destructive, arena-wide effects that reshape the battlefield.
His **wind affinity** allows him to perform bursts of movement and sweeping shockwaves — contrasting with his heavy frame.

---

## 🩸 **Phase 1: Molten Awakening (100%–70%)**

Ironhoof begins the battle slow but deliberate, testing the strength of his attackers.

**Abilities:**

1. **Tremor Slam** — Slams his warhammer into the ground, creating shockwaves that travel outward.
   *Each wave deals physical + earth damage and knocks down small NPCs (players are staggered instead).*

2. **Earthen Bulwark** — Raises spires of stone around himself, blocking line of sight for 10s.
   Players can destroy them to clear space, but each destroyed pillar grants Ironhoof 5 Rage.

3. **Fiery Charge** — Rushes forward in a straight line, dealing massive damage and knocking enemies aside.
   Leaves behind **Molten Trails** that burn for 8s.

4. **Molten Hide (Passive)** — Melee attackers take minor Fire damage every hit.
   When Rage exceeds 50, the damage reflection doubles.

**Phase Mechanic:**
After every 25% health lost, **lava vents** open around the arena, forcing players to reposition or suffer escalating Fire DoT.

---

## 🌪️ **Phase 2: The Shattered Plateau (70%–40%)**

Ironhoof begins to use wind energy channeled through his hammer — increasing both mobility and destructive range.

**Abilities:**

1. **Gale Roar** — A powerful bellow that pushes players back 20m and deals Wind damage.
   Interrupts casting and applies *Unsteady* debuff (reducing accuracy and evasion by 15% for 8s).

2. **Stormhoof Leap** — Jumps to a random location, landing with an **Earthshatter** that causes falling debris for 6s.
   Players too close on landing are stunned.

3. **Earthen Cyclone** — Spins his hammer in a full arc, creating a vortex that pulls in nearby enemies and flings them outward after 3s.

4. **Obsidian Barricade (Rage Ability)** — At 100 Rage, he slams his hammer and creates **ring walls of molten rock** around random players, trapping them temporarily.
   *(Walls can be broken but have high HP.)*

**Phase Mechanic:**
His armor begins to crack, exposing glowing magma lines — melee hits now cause minor Fire splash damage around their target.

---

## 🔥 **Phase 3: The Ravager’s Wrath (40%–0%)**

Ironhoof enters a berserk trance. The ground shakes continuously, and molten storms rage across the plateau.

**Abilities:**

1. **Earthbreaker Roar** — Emits a roar so powerful that it causes boulders to rain from the cliffs for 10s.
   Players must hide behind surviving pillars or terrain for safety.

2. **Furnace Heart (Passive)** — Upon reaching 30% HP, becomes **immune to knockbacks and roots**.
   Attack speed +30%, movement speed +20%.

3. **Crushing Combo** — Alternates between three melee attacks:

   * *Hammer Uppercut* (launches target),
   * *Ground Smash* (AoE stun),
   * *Wind Slice* (cone AoE).
     Each combo grows faster as his health decreases.

4. **Fiery Maelstrom (Ultimate)** — At 10% HP, Ironhoof channels his remaining energy, summoning a **spiral of molten rock and wind** around him for 20s.
   Any target inside suffers increasing Fire & Physical damage per second.
   Players must focus burst damage to end him before the vortex collapses.

---

### 💀 **Defeat Mechanics**

Upon death, Ironhoof’s body solidifies into blackened obsidian before shattering.
The molten forges dim, leaving behind **“The Ember of Ironhoof”**, a rare relic usable in crafting high-tier weapon augmentations.

**Victory Buff (Local Effect):**
Players near the arena gain **“Echo of the Ravager”** — +10% Earth and Wind resistance for 30 minutes.

---

### 🧩 **Shared Commander Mechanic (Universal Trait)**

Like other Sentry Commanders, Ironhoof uses **Rage** instead of mana.
He gains +10 Rage for each enemy within 10 meters and an additional +5 per 5% HP lost.
When reaching 100 Rage, he triggers one of his **Rage Abilities**, always escalating the fight dynamically.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

		Molten Wardens & Windforged Centurions

*(Champions of Ironhoof the Ravager – Gandarrin Fields / Outland Territories)*

**Lore:**
Before Ironhoof rose as the Ravager, he commanded legions of elemental guardians forged in the heart of ancient storms and molten caverns. The **Molten Wardens** and **Windforged Centurions** are the remnants of that force — half-living constructs bound to his rage and forged by the elements themselves. They march ahead of their master, shattering defenses and calling the winds and earth to his aid.

---

#### 🪨 **Molten Warden**

* **Element:** Earth / Fire
* **Role:** Frontline bruiser, AoE disruptor
* **Health:** High
* **Armor:** Heavy (resistant to ranged and fire damage)
* **Combat Style:** Close-quarters, punishing melee; slow but relentless.
* **Rage Mechanic:** Gains 1 Rage per second when not struck; at 100 Rage, explodes with *Lava Burst*.

**Abilities:**

1. **Lava Burst (Rage Skill)** – Releases molten shockwaves in a 12m radius, dealing fire damage and leaving burning ground for 8s.
2. **Crushing Tremor** – Slams the ground, creating a small earthquake that knocks down players in front.
3. **Searing Carapace (Passive)** – Reflects 5% of melee damage as fire; players with sustained contact take stacking burn.
4. **Magma Chains** – Roots one target in molten chains for 5s; breaking the root deals minor AoE fire damage.

**Unique Trait – Core Overload:**
When reduced below 25% HP, the Molten Warden channels for 6s, glowing red-hot. If not interrupted, it self-destructs in a **Fiery Implosion**, dealing massive AoE fire damage but leaving a **Molten Core Fragment** behind — destroying the fragment grants players temporary fire resistance (+15%) for 60s.

---

#### 🌪️ **Windforged Centurion**

* **Element:** Wind / Earth
* **Role:** Mobile skirmisher, anti-ranged unit
* **Health:** Medium
* **Armor:** Moderate (vulnerable to lightning damage)
* **Combat Style:** Quick, unpredictable strikes and mobility-based control.
* **Rage Mechanic:** Gains Rage per successful dodge or parry; consumes Rage to unleash devastating bursts.

**Abilities:**

1. **Tempest Dash** – Dashes between 3 nearby targets, dealing physical + wind damage; cannot hit the same target twice.
2. **Cyclone Guard (Rage Skill)** – Summons a spinning barrier of wind that reflects 50% of incoming ranged projectiles for 6s.
3. **Gale Strike** – Sweeping attack that deals heavy damage in an arc; players hit are knocked back 6m.
4. **Earthen Momentum (Passive)** – Each movement skill increases armor by 10% for 4s (stackable 3x).

**Unique Trait – Skybreaker’s Call:**
When the Centurion drops below 30% HP, it channels wind energy to summon a localized storm for 10s. The storm periodically strikes players in the area with lightning bolts and increases all Sentry movement speed by +25%.

---

#### ⚙️ **Synergy Mechanics**

When both champions are active simultaneously:

* The **Molten Warden**’s *Lava Burst* empowers the **Windforged Centurion**, granting its attacks bonus fire damage.
* The **Windforged Centurion**’s *Cyclone Guard* amplifies the **Molten Warden’s** *Tremor Slam*, extending its knockdown radius by 2m.
  If either champion falls, the other immediately enrages — gaining +50% Rage generation for 15s.

---

#### 💀 **Defeat Effects**

* Both drop **Fragments of the Ravager’s Sigil**, an event-only item that slightly weakens Ironhoof’s defenses if collected by players before his appearance.
* Defeating both within 5 minutes of each other grants the server-wide buff:

  > **“Echoes of the Forge” – Physical Resistance +5%, Fire Damage +10% for 30 minutes.**

---