			Character Overview

	In the "World Game", a "Character" refers to a player's interactive persona within the game. Players can create and control "Player Characters" (PCs), while 
the game controls "Non-Player Characters" (NPCs). Each player account is limited to creating "5 characters".

	Character Attributes :
- Class : The role or profession a character fulfills, such as tank, assassin, or healer.
- Race : The species or type of being a character is, such as warior, vampire, or werewolf.
- Faction : The group or alignment the character belongs to (e.g., ally or enemy factions).
- Talents : The character's special abilities or skills.
- Profession : The character’s craft or trade skills (e.g., blacksmithing, alchemy).
- Equipment : Items, weapons, armor, and accessories that enhance the character's abilities.

---

		Character Creation & Management

	Character Selection Screen :
The "Character Selection Screen" is where players can manage their characters. It includes the following options:
- Create New Character : Opens the character creation screen where you can select race, gender, and class, as well as customize appearance.
- Select Character : Displays a list of existing characters, showing their name, level, current location, and rest state.
- Delete Character : Allows players to permanently delete a character by following a process involving a deletion code.

		Creating a New Character :
- First Time Creation : When a player logs into a new server or game for the first time, they are automatically directed to the character creation screen.
- Choices : Players select a "race", "gender", and "class" for their new character. These choices are permanent, with class changes available through paid services,
but race cannot be changed after creation.
- Customization : The appearance of the character can be modified, including options for face, hair, skin color, and race-specific features. The Randomize button 
can also generate random combinations.
- Naming : Players choose a character name. The Randomize button can generate random names based on the selected race and gender. Names are permanent unless a paid 
"Name Change" service is used.
- Start Level : New characters typically start at level "1".

		Deleting a Character :
	To delete a character:
1. Request a Delete Code : This is done through the website account section.
2. Enter the Code : Players must enter the code received via email, followed by typing "DELETE" to confirm deletion.
3. Permanent Deletion : Once confirmed, the character and all associated gear/items are permanently erased from the account.

		Restoring Deleted Characters :
	Players can restore deleted characters under specific conditions:
- Eligibility for Restoration : Characters deleted at level 60 or higher can always be restored, while others have time limits based on level:
	- Level 10-29: Eligible for 90 days.
	- Level 30-59: Eligible for 120 days.
	- Level under 10: Not eligible for restoration.
- Undeletion Service : Characters can be restored once every 30 days, with all gear, items, enchantments, and gems intact.
- Name Conflicts : If a deleted character's name matches an existing one, the current character must be renamed, transferred, or deleted to restore the deleted 
character.

		Character Customization :
- Appearance Changes : After creation, players can change certain aspects of their appearance, such as hair, face, and skin color, by different ways within in-game.
- Class Changes : Players can change their character’s class via a paid "Class Change" service, but the race cannot be changed by any means after creation.

		Notes on Character Names :
- Random Name Generation : Random names generated by the Randomize button are based on race and gender, but they may repeat if used multiple times. Restarting the 
game client can generate new suggestions.