			Reefy the Otter

	Location : Middlean Islands / Capital City / East Side District / The Academy of Development / Freshwater Plunge

---

	Appearance : Reefy is a small but remarkably agile river otter with sleek dark-brown fur that shines whenever he emerges from the freshwater pools. His chest 
and muzzle are covered in lighter silver-gray fur, giving him a distinctive appearance that makes him instantly recognizable among the regular visitors of 
"Freshwater Plunge". Around his neck rests a small blue cloth collar decorated with polished shells and tiny fishing charms gifted to him by local fishermen over 
the years. His bright black eyes constantly dart around with curiosity and intelligence, and his whiskers twitch excitedly whenever players approach the water’s 
edge. Reefy moves with incredible speed and fluidity through the pools, often diving beneath the surface only to reappear unexpectedly nearby carrying pebbles, 
shells, or occasionally lost objects in his paws.

---

	Personality : Reefy is playful, energetic, and unusually intelligent for a tame otter. He has become beloved by both fishermen and swimmers around Freshwater 
Plunge because of his friendly nature and amusing behavior. Unlike ordinary animals, Reefy appears highly aware of the people around him and often reacts 
differently depending on how players behave near the water. He enjoys following active swimmers, playing games with children and apprentices, and assisting 
fishermen searching for dropped items underwater. While mischievous at times, Reefy never behaves aggressively and seems especially fond of players who spend time 
swimming or practicing fishing techniques around the pools.

---

	Behaviour : "Reefy" constantly swims through the freshwater pools, diving beneath platforms, weaving between swimmers, and occasionally floating calmly on his 
back near the shoreline. He frequently performs playful tricks such as spinning underwater, balancing shells on his nose, or splashing players standing too close to
the edge. Sometimes he disappears beneath the surface for several moments before returning with small objects retrieved from the bottom of the pool. During quiet 
periods, Reefy may follow certain players through the water or guide them toward hidden underwater corners and submerged pathways around Freshwater Plunge.

---

	Role :

* Role(s) : Friendly Companion, Support Creature
	Reefy serves as both an atmosphere companion and a minor interactive helper NPC within "Freshwater Plunge". His presence reinforces the lively and welcoming 
atmosphere of the building while also assisting players with small underwater interactions and aquatic exploration activities.

---

	Mechanics :

* Type : Companion NPC, Interactive Support NPC
* Reputation : Indirectly connected to Fisherman-related atmosphere and aquatic training interactions.
* Interaction Limitations : Available to all players. Some interactions are enhanced for players with the Fisherman Profession.
* PvP : Cannot be targeted, attacked, or harmed. Protected NPC creature.
* Respawn Time : Instant (non-combat companion NPC).
* Other Mechanics :
	* Reefy occasionally retrieves small lost items dropped into the pool by players.
	* Players may interact with Reefy to initiate short swimming mini-games or underwater retrieval activities.
	* Sometimes guides players toward hidden underwater objects, gathering spots, or submerged entrances within Freshwater Plunge.
	* Fisherman Profession players may occasionally receive small temporary buffs after playing with Reefy, such as minor swimming speed increases or slightly 
improved underwater visibility.
	* During crowded periods, Reefy performs random playful animations and interactions that contribute to the social atmosphere generated by the Capital Life & 
Activity System (CLAS).
	* Rarely, Reefy may bring players uncommon shells, aquatic herbs, or decorative trinkets from the bottom of the freshwater pools.

---

	Skills :

* Skill 1 : "Underwater Retrieval"
	* Description : Reefy can dive into deeper sections of the freshwater pools to locate and recover small submerged objects.
	* Effect : Helps players recover training objects, fishing tools, or hidden interaction items.

* Skill 2 : "Otter’s Guidance"
	* Description : Reefy occasionally leads players toward hidden underwater pathways or submerged points of interest around Freshwater Plunge.
	* Effect : Temporarily highlights nearby underwater interactable objects or hidden gathering spots.

* Skill 3 : "Playful Encouragement"
	* Description : After positive interactions, Reefy becomes excited and swims alongside players during aquatic activities.
	* Effect : Grants a small temporary swimming speed and underwater stamina regeneration bonus.

---

	Quest :

Reefy the Otter does not offer traditional quests, though he may trigger hidden environmental interactions or playful mini-events tied to underwater exploration.

---

	Quotes :

* "Reefy chirps happily and splashes water toward you."
* "The otter dives beneath the surface and resurfaces holding a smooth shell."
* "Reefy spins in the water before floating calmly on his back."
* "The otter nudges your hand before darting underwater again."
* "Reefy chitters excitedly while circling around nearby swimmers."
* "The otter taps the water repeatedly as if trying to show you something below."
* "Reefy disappears underwater for several seconds before returning with a shiny pebble."
* "The playful otter splashes nearby fishermen before quickly swimming away."
* "Reefy tilts his head curiously while watching your movements in the pool."
* "The otter seems eager for you to follow him underwater."

---
