			Marlen Dunwick - Cargo Inspector

## **Name:**
**Marlen Dunwick**

## **Role:**
Port Authority / Quest NPC

## **Type:**
Civilian – Dock Official – Quest Giver

## **Function:**
Oversees cargo integrity and prevents contraband smuggling in the Landing Port of Southfall.
Primary NPC for quests related to dock operations, suspicious cargo, and early investigative content.

---

# **Overview**

Marlen Dunwick is the senior Cargo Inspector in **Southfall Port**, responsible for ensuring that every crate, barrel, and shipment entering Netar Island complies with island trade law.
Experienced, sharp-eyed, and notoriously difficult to deceive, Dunwick plays an early role in the player’s exposure to the island’s criminal undercurrent.

Marlen is the NPC who responds to items and events generated by the “Suspicious Cargo” mechanic—especially the **Contraband Ledger**, which he immediately recognizes as coded smuggler intel.

He stands near the central inspection platform, where workers bring crates for tagging and approval.

This NPC is essential because:

* He introduces the player to the smuggler threat.
* He acts as the anchor NPC for the dock sub-storyline.
* He awards minor early-game reputation with the Dockworkers’ Syndicate.
* He provides access to “dock maintenance” and “inspection” themed side content.

---

# **Appearance**

Marlen Dunwick has the look of a man who has worked the docks for decades:

* Wears a **dark blue port authority coat** with brass clasps.
* Thick leather belt with a bundle of **inspection tags** and a small seal punch.
* Brown work trousers tucked into waterproof boots.
* Short gray hair, close-trimmed beard.
* Eyes narrowed, analytical, constantly scanning his surroundings.
* Holds a heavy **clipboard carved from driftwood**, etched with his personal seal.
* A quill tucked behind one ear.
* A large magnifying monocle hanging from a chain on his chest.

Idle animation:

* Taps the clipboard.
* Inspects crates even when not interacting with players.
* Occasionally shouts at workers to “lift properly” or “watch the edges.”

---

# **Behavior & Interaction**

### **General Behavior**

* Patrols a short 6–10 meter loop around the inspection platform.
* Stops to inspect crates periodically.
* Occasionally berates lazy dockhands.
* Cannot be harmed or engaged in combat.

### **Player Interaction**

Marlen reacts differently based on context:

**1. Basic Interaction**

* Provides minor lore about cargo routes, ship arrivals, and port rules.
* Offers general tips about interacting with dock systems (crates, merchants, etc.)

**2. When handed a Contraband Ledger**

* Immediately shifts tone into urgency.
* Starts the quest continuation event chain.

**3. Reputation Effects**
As players gain reputation with Dockworkers:

* He gives more friendly dialogue.
* Later unlocks a luggage-tag cosmetic or a “Dockworker’s Gloves” cosmetic prize.

---

# **Mechanics and Functions**

### **• Quest Giver**

* Primary NPC for quests involving:

  * Smuggling Shenanigans storyline
  * Cargo purity inspections
  * Dock maintenance activities (later optional)

### **• Event Anchor**

* When “Suspicious Cargo” rare event completes, Marlen reacts with commentary (only for flavor).

### **• Environmental Interaction:**

* Occasionally points out crates that look “tampered” (purely flavor).

### **• Anti-Abuse Mechanics**

* Players can only turn in 1 Contraband Ledger per 24 hours (ledger is unique per drop).
* Marlen avoids giving reputation beyond intended caps.

---

# **Dialogue / Quotes**

### **General Idle Quotes**

* “Crates don’t inspect themselves… unfortunately.”
* “Seal that tighter! Do you want another infestation?!”
* “If one more ship arrives late, I’ll personally swim out to drag it here.”

### **Interaction (No Quest Item)**

* “Let’s hope your cargo is cleaner than the last batch.”
* “State your business on these docks.”
* “Watch your step. We’ve had… incidents.”

### **When Given the Contraband Ledger**

* “Where did you get this? These codes aren’t used by the Port Authority…”
* “This… this is bad. Very bad. Someone is moving goods without clearance.”
* “Stay close. I need your help with this.”

### **Quest Acceptance**

* “If this ledger is real, we’re dealing with professionals. Smugglers with reach.”

### **Quest Completion Later**

(We will write full lines after developing the quest chain.)

---

Perfect.
Below is the **full questline** that begins when the player obtains the **Contraband Ledger** from the Suspicious Cargo rare event.

This questline is **self-contained**, has **no ties to future content**, and rewards **Reputation with the Navigator’s Lodge** from the Capital City (your instruction).

It consists of **3 quests total**, forming a complete micro-story arc entirely within the Landing Port of Southfall.

---

# 🌊 **QUESTLINE: “Contraband in the Current”**

## *(Triggered by looting the **Contraband Ledger**)*

# **QUEST 1 — “Ledger of Lies”**

### **Quest Type:**

Story / Investigation

### **Quest Giver:**

Cargo Inspector **Marlen Dunwick**

### **Quest Start Item:**

**Contraband Ledger**
A small water-damaged notebook with coded marks and unusual shorthand symbols. A faint smell of seawood and bitter oils clings to it.

---

## **Quest Start (Hand Item to Marlen)**

**Marlen Dunwick:**

> “Let me see that… This isn’t one of ours. These codes don’t belong to any sanctioned merchant route.
> Someone at this port thinks they can move goods under my nose.”

> “This ledger’s incomplete. Whoever dropped it must have been in a hurry.
> We’ll need more evidence if we’re to act on this.”

---

## **Objectives:**

* **Inspect 3 Suspicious Crates** around the Landing Port
* **Find “Illicit Parcel Fragment”** inside one of the crates
* Return to **Marlen Dunwick**

### **Mechanic:**

3 crates with faint markings will spawn in fixed but cycling locations near the dock.
Player interacts → 2 crates contain nothing → 1 contains:

**Illicit Parcel Fragment**
A torn scrap of thick fabric stamped with a foreign wax seal.

---

## **Quest Completion Dialogue**

**Marlen Dunwick:**

> “A torn parcel with a foreign seal… this confirms it. These smugglers aren’t local.
> They’re routing goods from Capital Island without Navigator’s Lodge approval.”

> “If the Lodge hears about this, they’ll want names.
> And they’ll compensate those who assisted.”

**Reward:**

* **500 Navigator’s Lodge REP**
* **30 Gold**
* Unlocks next quest.

---

# **QUEST 2 — “The Dockside Pursuit”**

### **Quest Type:**

Solo Mini-Encounter / Chase

### **Quest Giver:**

Marlen Dunwick

---

## **Quest Offer Dialogue**

**Marlen Dunwick:**

> “I saw someone skulking near the eastern supply racks earlier—hood up, gloves on, carrying something small.
> When I called out, he bolted.
> If he’s tied to that ledger, he’ll try to flee the port entirely.”

> “Find him. Bring back whatever he’s hiding.”

---

## **Objectives:**

* **Chase the Suspicious Runner**
* Interrupt him before he reaches the end of the pier
* Loot the stolen item: **Contraband Manifest Token**
* Return to Marlen

### **Mechanic:**

A non-combat NPC appears and begins running a set escape route.

Player must:

* Interact with **Footprints** to trigger his spawn
* Sprint after him
* Use any movement ability or a “Shout” interaction (appears on screen) to slow him
* When caught, he despawns in smoke and drops a token

---

## **Item Looted:**

### **Contraband Manifest Token**

A triangular brass token with the initials **“R.M.”** engraved.
Used by smugglers to approve illegal cargo.
Clearly *not* from the port authority.

---

## **Quest Completion Dialogue**

**Marlen Dunwick:**

> “A smuggler manifest token…
> These are used only by the outlaw groups operating out of the Great Sea’s shadow routes.”

> “The Navigator’s Lodge will want this immediately.
> You’ve done excellent work.”

**Rewards:**

* **700 Navigator’s Lodge REP**
* **60 Gold**
* Unlocks final quest.

---

# **QUEST 3 — “Report to the Lodge”**

*(Final)*

### **Quest Type:**

Report / Delivery

### **Quest Giver:**

Automatically unlocked after Quest 2
Quest Hand-in NPC is in **Southfall Port**, not Capital City (per instruction: self-contained).

---

## **Quest Offer Dialogue (from Marlen)**

**Marlen Dunwick:**

> “You’ve helped uncover a real smuggling line, one operating through *my* docks.
> The Navigator’s Lodge needs a full report before they start pointing fingers at innocent workers.”

> “Deliver your findings to their local representative.
> She’s on the upper dock balcony—usually reading maps.”

---

## **Objectives:**

* Bring the **Contraband Manifest Token** and the **Illicit Parcel Fragment** to
  **Navigator’s Lodge Officer: Lira Seastone**
* Speak with her about your findings
* Receive your commendation

---

# **NPC: Lira Seastone** (Short Description)

A calm, disciplined woman in navy-blue Navigator’s Lodge attire.
She monitors Southfall’s port activity on behalf of Capital Island.

---

## **Hand-In Dialogue (Lira Seastone)**

> “Inspector Dunwick’s report reached me before you did.
> Let’s see the evidence…”

She examines the items with a trained eye.

> “These markings—yes. This confirms smuggling activity bypassing Lodge routes.
> We’ll begin a formal inquiry immediately.”

> “Your assistance is appreciated. The Lodge values those who safeguard proper trade.”

---

## **Final Rewards:**

* **1,200 Navigator’s Lodge REP**
* **Navigator’s Crest (Common Trinket)**

  * +1% movement speed while in port towns
  * Cosmetic sigil appears faintly on character belt
* **55 Gold**

---