			Heal over Time (HoT)

	Definition :   
	"Heal over Time" (abbreviated as HoT) refers to a type of healing ability where a target is healed gradually over a specified duration, rather than receiving 
all the healing at once. In "World Game", HoT healing typically occurs in periodic intervals (e.g., every few seconds), allowing for sustained recovery during combat or other dangerous situations.

	Key Characteristics	  
- Gradual Healing : Instead of providing an immediate burst of health, HoTs apply healing over time, restoring health at regular intervals. This can be crucial for ongoing damage absorption in prolonged fights.
  
- Target-Specific or AoE :  
   - Most HoTs are target-specific, meaning they heal a single character or creature.
   - Some HoTs are "Area of Effect" (AoE), such as Healer spells that heal multiple characters within a defined radius, providing support to entire groups.

- Buff-Like Effect : While a HoT is essentially a type of buff, it has a much shorter duration compared to traditional buffs. HoTs can usually be dispelled or removed, much like standard buffs.

	Classes Using HoT  
- Healers and Sorcerers : The most common users of HoT abilities, often relying on them to keep party members healed without needing constant direct healing.
  
- Tank Classes : While tanks typically focus on absorbing damage, some have HoT abilities that heal them over time, aiding their survivability. These methods differ from the straightforward healing buffs used by Healers.

- Hunters : These professions also have HoT abilities, but they are often limited to healing themselves or their pets, and are not as frequently seen in other contexts.

	Limitations  
- Stacking HoTs : It is not possible to stack the same HoT from a single healer on one target. However, HoTs from different healers can stack, allowing multiple sources of healing over time.
- Mana Efficiency : HoTs can be inefficient if used on characters who are not expected to take damage, as it wastes mana on unnecessary healing.

	Tips
- Avoid Wasting Mana : Don’t apply a HoT to a character who isn’t expected to take damage. Using HoTs efficiently ensures mana is spent wisely and helps avoid unnecessary aggro generation.
  
- Aggro Considerations :  
   - Each tick of a HoT generates a small amount of aggro over time, allowing the tank to build sufficient aggro to keep enemies focused on them.
   - Unlike direct heals, which cause a sudden burst of aggro, HoTs create a continuous flow of aggro, making them easier to manage in combat situations.
   - Aggro generated by HoTs is spread over time, ensuring that threat is distributed more evenly and doesn't spike suddenly.

- HoT on Tanks : It is generally a good idea to apply a HoT to your tank as they begin taking damage, but only if they can generate sufficient aggro to manage the threat. A skilled tank can often generate more aggro per tick than the HoT itself, ensuring that the enemies stay focused on them.

		Additional Notes**
- In "Dungeons" or "Instances", where large groups of monsters are present, players using HoTs should be careful to stay at a safe distance. HoTs tend to generate aggro from the moment they are applied, and standing too close to the crowd of enemies can lead to unwanted attention from monsters, especially those that target easier prey.