			Auction House

	The Auction House is a wonderful place to find what you need or even make some money for yourself. You can find or sell weapons, armor, trade goods, recipes and 
reagents. Auction House fees and deposit costs are also one of the largest gold sinks in the game and is made for a fast item selling method different from normal 
"Market Place" in "Market Plaza" where people put own shops with goods for sell and pay no fee but each player must go to check individual one by one every shop 
generated by others without to bind for any items that are affordable or neccesary to purchase.
	All major cities and "Market Plaza" have their own Auction Houses. All Auction Houses in a realm are connected, and offer the same items for sale, regardless of 
location or faction. 

	Characters on the same account cannot bid on items put up for auction on any Auction House by a different character on the same account.

		Auction system mechanics
	Opening the Auction House dialog

	Right-click on one of the auctioneer NPC's to open a dialog box where you can interface with the auction system. These NPC's always have the title Auctioneer and 
you can find them on your Minimap by checking Auctioneers. The gold coins icon shows where they are. The dialog has three tabs, Browse, Bids, and Auctions, located 
at the bottom. Buyers will need the first tab to find an item to bid on, and the second tab to track current bids. Sellers will need the first tab to check 
prevailing prices, and the third tab to track the items they currently have on sale.
	
	
	Finding items
	
	The dialog starts on Browse tab where you can find items currently for sale. If you know the name of what you wish to find, simply enter all or part of it in the
Name box, and click the Search button on the upper right, and the system will list all the items that match the string you entered. If you already have the item in 
your bags, most likely because you want to check the market on an item you want to put up for sale, Shift-click the item and the name will be filled into the box for
you, avoiding any spelling issues.
	If you don't have a specific item in mind, there are other ways to narrow down the list from the many hundreds of items available. To search for a specific 
category, click on one of the headings (weapon, armor, spell, recipe, etc.) on the left. Most categories have sub-categories, and many of these have 
sub-sub-categories, so you can choose how narrow the search will be. For example, you can list just Armor, just Leather Armor, or just Leather Armor for the Head. 
	Click Search any time you want to find items that match the current options, or click Reset to clear the existing criteria and start over.
	If you're looking for a specific range of levels, useful for weapons and armor, fill in the level range next to Name box. Note that this refers to the 'Required 
level to use' property, not the Item Level. So, for example, it your current level is 25 and you're looking to upgrade you Dagger, select Weapons/One-Handed/Daggers 
as your category, and a level range of 20 to 25. Next to the level range is a box that allows you to narrow down the list to items of a specific quality. Only items 
that match the selected level (Poor, Common, Uncommon, Rare, etc,) or above will be shown.
	Next to the quality box are check-boxes for Usable Items and Display on Character. If Usable Items is checked then only items which you can currently equip or 
otherwise use are shown. For example, if the category Recipes is selected and Usable Items is checked, then only those recipes which you can learn with your current 
professions and skill levels, and haven't already learned, will be listed. 
	
	
	Items for sale

	A list of the items matching the conditions you set, if there are any for sale, will be displayed in the right pane of the dialog. Note that if no items appear 
it could be because none happen to be on sale, even though a matching item may exist in the game. The list of items for sale includes:
*Item icon (including quantity) and name. The icon is redded out if it's not usable by your character.
*Required level to use item. Again, this is not the same as the Item Level.
*Time left on the auction:
	Short - Less than 30 minutes.
	Medium - Between 30 minutes and 2 hours.
	Long - Between 2 hours and 12 hours.
	Very Long - Between 12 hours and 48 hours.
*Two Prices: the current bid and the buyout price. All prices are given in Gold, Silver, Insignia, other currency.

	Click on one of the column headings to change the order in which the items are listed, and click a second time to toggle between ascending and descending. The 
possible sorting options are Rarity, Level, Time Left, Seller, and Price per Unit. The Price per Unit sort goes by the Buyout price and items without a buyout price 
set are listed last.


	Buying an item

	To place a bid on an item, click on it and press the Bid button on the lower left of the dialog. The amount of the bid is deducted from your current cash and, 
assuming that no one places a higher bid before the auction expires, you'll receive the item in the mail. The amount of the bid will default to either be the 
initial bid amount set by the seller, or the next highest bid amount if there is an existing bid. You can adjust this amount in the price entry areas at the bottom 
of the dialog. When you place a bid, the amount is placed in escrow until the auction is over and you get the cash back in the mail if you lose the auction.
	If you don't want to wait for the auction to expire, then press the Buyout button instead to pay the Buyout price and get the item in the mail right away. The 
Buyout price is usually higher than the Bid price as a premium for getting the item quickly. A Buyout price isn't always set though, in which case is only option is 
to place a bid.

	
	Selling items
	
	To sell an item, select the rightmost Auction tab at the bottom of the screen. But before doing so, you might want to search for the item in the browse screen to
get an idea of how many are currently on sale and the going price. When the auction pane comes up, drag an item from your inventory to the Auction Item slot on the 
upper left. For non-stackable items, all you have to do next is enter the price at which you want bidding to start, and the Auction Duration (12, 24, or 48 hours). It is often a good idea to set a buyout price. These amounts may be the same, or different, as is the player's wish, but the buyout price cannot be lower than the 
minimum bid price. The bid suggested when you place an item up for auction is 150% of the vendor sell price (VSP). The minimum starting bid is 1 silver. Items with 
no sell value will suggest a bid of 1 silver aswell.
	For stackable items you also need to set a stack size. Since buyers can't break up a stack when they buy, it may be a good idea to break up large stacks when 
you create the auction. You can set the bid and buyout prices per item or per stack according to the selection box at the top of the pricing area. Make the Number of
Stacks value greater than 1 to create multiple auctions at once, but it has led to the auction house being flooded with single stack items. This can be beneficial to
the seller, as it means that people can buy the exact amount of an item that they want, but it may also mean that people who sell in single stacks lose money, as 
many people will want to buy items in relatively large stacks (see Auction House tips). When you're ready, press the Create Auction button to place the item on 
sale. A deposit will be deducted from your available cash and the item now appears in the list of items you have for sale in the right pane of the dialog.
	You can cancel any auction by clicking the item and clicking the Cancel Auction button at the bottom of the screen. However, you will lose the deposit that you 
paid when first placing the item up for auction.


	Deposits

	The deposit fee, or listing fee, is the amount of money needed to place an item up for auction. It depends on the item's vendor sell price (VSP) and the amount 
of time you want to put the item up for auction. The deposit is paid immediately when you list the item. If the calculated deposit fee is fewer than 1s (including 
the case when item has no vendor sell price, VSP=0), then final deposit fee will be 1s. 


	Fees
	
	When you successfully sell an item on the auction house, the house will take 5% of the winning bid as its cut. The amount of money you will receive by mail will 
be the winning bid, minus the cut, plus the return of your deposit:

		Amount Received = Winning Bid - Cut + Deposit
			= Winning Bid*(0.95) + Deposit
	When an item fails to sell, you will receive the item in the mail, but your deposit will not be refunded. When you cancel an auction that has no bids placed on 
it, you simply lose your deposit, and the item is returned to you by mail. When you cancel an auction that has a bid in place, you will lose your deposit plus a fee 
equal to the house cut of the current bid. Note that you can't bid on an item which you placed on auction to avoid paying the deposit, even if you use another 
character on the same account. In most cases the house cut would be more than the deposit anyway.

