			Character
			
	Character refers to an interactive representation of a game persona. Characters may be controlled by players (player characters or PCs) or by the game (non-
player characters or NPCs).
	The maximum number of characters per user account is 5. 
	Characteristics include: class, race, faction, talents, profession, and equipment.

		Character selection screen
	At the Character Selection screen, you can make a new character, choose a character to play, access tech support, and adjust your account settings.
	
	Create New Character
Clicking the Create New Character button takes you to the character creation screen, where you can generate a character to play in the game.
The right side of the Character Selection screen lists any characters you have created. If you haven’t yet made any characters, this area is blank. You can have up 
to 5 characters, which is the account limit. Each character entry shows the character's name, level, current location, and rest state. Clicking on a character 
displays it in the center of your screen.

	Delete Character
To delete a character, select that character and then press the Delete Character button. You will be prompted to confirm the deletion. For this you must request via 
website account in specific section a delete code for it. ONce you have the code via email, tape it in the section and click the Okay button to permanently erase 
that character.

		Creating characters
	
	New characters can be created from the character selection screen by clicking the Create A New Character button, which will open the character creation screen. 
	When choosing a new server for the first time, the player is automatically taken to the character creation screen.
	
	The character creation screen allows the player to choose a race, gender, and class for their new character. Note that the race and class choices are essentially
permanent, and once the character is created cannot be changed in-game. A character's class can be changed through a paid service outside the game itself, namely 
the Class Change, but it is not possible to change an existing character's race by any means.
	Once the race, class, and gender are chosen, the player can then customize several aspects of their character's appearance, including their face, hair, skin 
color and race-specific options. Each of these features can be adjusted individually, or the player can try random combinations through the Randomize button. All of 
these features and the gender can later be changed by visiting a barbershop in-game.
	Finally, the player must choose a name for their character.The Randomize button can be used to generate random names, in keeping with the race and gender chosen.
	The choice of the name is permanent unless the paid Name Change service is used.
	
	Once the player is happy with all of their selections, the character itself is created, and immediately becomes available for play. New characters normally start
at level 1.
	On public test realms and during beta testing, players may be able to create template characters through a special button from the character selection screen.
	
	Notes
The random names generated by the Randomize button appear to be composed of basic elements which are randomly combined in various possible forms. While the list of 
possible names is quite extensive, it does appear to be limited, and if the feature is used repeatedly will eventually repeat suggestions. A new selection of 
suggestions can, however, be generated by quitting and relaunching the game client. This appears to generate a new random selection and can be useful if none of the 
offered suggestions are to the player's liking.

		Deleting characters
	Characters can be deleted from the character selection screen once was made a request of "Delete Code" on the website account, with the player required to 
manually type the respective code that was send via email and second section to type : "DELETE" in order to confirm the action. Once deleted, the character will no 
longer be shown or be available for play.

	Character deletion is permanent, and deleting a character will cause all gear and items to be lost. However, the Undelete Character feature can allow players to 
restore certain deleted characters but is made by a request via website account and request an external help from admins.

	Restoring deleted characters
Restore Deleted Character option allows the player to restore deleted characters, with a few limitations : 
*Undeleted characters will be restored with all items, gear, enchantments, and gems intact.
*Players can use the undeletion service a maximum of once every 30 days.
*If the player wishes to restore a character whose name matches one of their current characters on the same realm, the current character must first be renamed, transferred or deleted before the deleted character can be restored.

	Eligibility
Whether a character is available for undeletion depends on its level and the amount of time that has elapsed since it was deleted.

Characters under level 10 are not eligible to be undeleted.
Characters between level 10 and level 29 will be eligible for 90 days after deletion.
Characters between level 30 and 59 will be eligible for 120 days after deletion.
Deleted characters at level 60 and above will always be eligible for undeletion.

	