		Vampires and Werewolfs 
		
Your decision to keep vampires and werewolves both as physical damage classes while tying their mechanics to "Blood Orbs" is an excellent approach. This design ensures a clear thematic identity for each class and maintains balance in gameplay, especially in PvP scenarios. Additionally, adhering to the skill mechanics style of Metin2 rather than World of Warcraft gives the classes a more deliberate and tactical combat feel, which can further distinguish your game.

Here’s how this can be structured:

Blood Orb Mechanics
Core Mechanic:
"Blood Orbs" are central to both vampires and werewolves but serve distinct purposes:
For Vampires:

Increase movement agility (e.g., faster dodges or skill cooldown reductions).
Boost damage dealt with subsequent attacks.
Maintain combat flow, ensuring the character remains fluid and agile as long as they actively absorb orbs.
For Werewolves:

Grant temporary strength and resilience (e.g., damage absorption or health regeneration).
Enhance survivability, reinforcing their tanky role in combat.
Orb Absorption:
Blood Orbs can be generated by landing critical strikes, using certain skills, or defeating enemies.
Absorbing orbs could also temporarily grant a "Frenzy" or "Empowered" state.
Orbs decay after a short duration if not used, encouraging continuous combat.
Skill Mechanics:
Combat Style:
Skills follow Metin2’s sequential use mechanics:
Each skill is executed individually, with clear animations and cooldowns.
Chainable attacks depend on skill timing and player input, emphasizing tactical decisions rather than rapid-fire combinations.
This makes every skill meaningful, rewarding precision and timing.
Skill Types:
Vampire Skills:

Agile and precise, with mobility-based abilities and life-draining effects.
Skills could include:
"Piercing Talon": A high-speed lunge dealing critical damage.
"Shadow Step": A dash attack that leaves a bleeding effect.
"Blood Surge": Consumes stored orbs to temporarily increase attack speed and damage.
Werewolf Skills:

Focus on brute strength, AoE damage, and self-healing abilities.
Skills could include:
"Savage Rend": A wide-swinging claw attack dealing AoE damage.
"Howl of Fury": Buffs allies while intimidating enemies.
"Feral Resilience": Converts blood orbs into a shield absorbing incoming damage.
Skill Learning and Progression:
Skills are learned sequentially, tied to the character’s level and rank.
Mastery of skills comes with usage, unlocking enhancements like reduced cooldowns or increased damage.
PvP Balance Considerations:
Vampires vs. Werewolves:

Vampires have agility and precision, making them deadly in hit-and-run tactics.
Werewolves counter with resilience and sustained damage, excelling in prolonged engagements.
Against Other Classes:

The reliance on "Blood Orbs" makes vampires and werewolves vulnerable when disengaged, as their mechanics thrive in active combat.
Skill-based combat ensures that their strength relies on player timing and execution rather than overwhelming power.