			Money

		Overview
	In "World Game", money refers to various forms of currency such as "silver pieces", "gold pieces", and "platinum coins", as well as other specialized items. The
total amount of money a player has is shown in the bottom right of the inventory window, commonly referred to as "gold".

		Using Money
	Money in "World Game" is primarily used for the following purposes:
- "Vendor NPCs" : Purchase items or services.
- "Trading" : Exchange money for goods with other players.
- "Mail" : Send money to other players.
- "Flight" : Pay for a flight from the flight master.
- "Auction House" : Bid for items or deposit money for auctioning your own items.
- "Bank" : Buy additional bag slots or other services.
- "Stables" : Hunters can purchase stable slots for their pets from a stable master.

	Obtaining Money
Players can acquire money through various means:
- "Looting" : Killing mobs, finding treasure chests, or completing quest rewards.
- "Selling Items" : Sell unwanted items to vendor NPCs or to other players via the Auction House.
- "Trade or Mail" : Money can be received from other players directly via trade or mail.

	If a player uses money to put down a deposit for auctioning an item, they lose the deposit if the item doesn't sell or if the auction is canceled. Failed bids 
are returned to the player via mail.

	Types of Coins
- "Silver Coins" (also known as silver pieces or "s")
- "Gold Coins" (also known as gold pieces or "g")
- "Platinum Coins" (also known as "P") – This is converted by the character when they reach 1,000,000 gold. A small fee is charged for conversion by the Auctioneer or Store NPC.
- "Insignia" (PvP coin) – Earned through participation in Arena or Battlegrounds.
- "Diamonds" (also known as "D") – Used for purchases from the Item-Shop, these can only be generated by using real money.

	World Droppable Currency 
- "Needle of the Pine Tree" - drop currency that drop from majority of monsters found in "Garland".

	Special Currency Types
- "Spring Leaf" : Dropped by the **Winterspring Boss** and used for exchanging goods during the **Spring Ceremony** event.
- "Winter Magic" : Dropped by the **Winterspring Boss** and used for exchange during the **Spring Ceremony** event.

			Technical Considerations
	The amount of money in circulation within a server is dynamic. It can be "created" or "destroyed" based on player actions:

		Money Creation:
	Money is added to the player economy when:
- A player sells an item to a vendor.
- A player loots money from mobs or chests.
- A player completes a quest that rewards money.
- A player at the maximum level completes a quest with an experience reward, which is converted into money at a rate of 2 silver per experience point.

		Money Destruction:
	Money is removed from the economy when:
- A player buys an item from a vendor or trainer, or pays for a taxi flight.
- A player sends money via mail.
- A player pays for repairs.
- A player pays a deposit or commission to the Auction House.
- A player completes a quest with a monetary requirement.
- Players pay for services such as:
  - "Blacksmith"
  - "Horsekeeper"
  - "Pet Tamer"
  - "Tailor"
  - "Herbalist Trainer"
  - "Inner Core upgrades"

	Money traded between players does not affect the overall economy since it is a simple exchange of value.

		The Money Cycle
	As a new server starts, there is no money in circulation. Over time, money is generated through player activity such as killing mobs and completing quests. However, as the game progresses:
- "Money destruction" increases due to higher repair costs from better gear, more expensive mounts, and larger raids.
- Auction House activity also increases, and players pay a commission (5-15%) on each sale.
- As servers mature, there is a significant one-time destruction of money, especially as players buy mounts, training, and higher riding skills.